[package]
name = "incremental"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]


[dependencies]
cosmwasm-schema = "2.1.3"
cosmwasm-std = "2.1.1"
cw-storage-plus = "2.0.0"
cw-utils = "2.0.0"
serde = "1.0.204"
